server:
    port: 813
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: @mysql.url@
        username: @mysql.username@
        password: @mysql.password@
    redis:
        host: @redis.host@
        port: @redis.port@
        password: @redis.password@
        pool:
            max-idle: 100
            min-idle: 0
            max-active: 100
    mvc:
        throw-exception-if-no-handler-found: true
    resources:
        add-mappings: false
mybatis:
  type-aliases-package: com.xrom.server.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml